export const QUERY_TRENDING = 'QUERY_TRENDING';
export const QUERY_TRENDING_SUCCESS = 'QUERY_TRENDING_SUCCESS';
export const QUERY_TRENDING_ERROR = 'QUERY_TRENDING_ERROR';
export const QUERY_COMMENTS = 'QUERY_COMMENTS';
export const QUERY_COMMENTS_SUCCESS = 'QUERY_COMMENTS_SUCCESS';
export const QUERY_COMMENTS_ERROR = 'QUERY_COMMENTS_ERROR';
